<?php

namespace Database\Seeders;

use App\Models\Restaurante;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RestauranteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Restaurante::factory(10)->create();
        // Restaurante::create([
        //     'nombre_restaurante' => 'Mc Donalds',
        //     'ubicacion_restaurante' => 'Carrera 123, 456, Ciudad',
        //     'descripcion_restaurante' => 'Este es un restaurante de comida rápida y saborosa.',
        //     'horario_restaurante' => 'Lunes a Viernes: 11:00 AM a 1:00 PM, Sábado y Domingo: 11:00 AM a 3:00 PM',
        //     'precio_restaurante' => 15.00,
        //     'valoracion_media' => 1,
        //     'img_restaurante' => 'mc_donalds.png',
        //     'nombre_gerente' => 'Gerente',
        //     'email_gerente' => 'gerente@example.com',
        // ]);

        // Array con 50 restaurantes
        $restaurantes = [
            [
                'nombre_restaurante' => 'La Torre de Oro',
                'ubicacion_restaurante' => 'Av. de la Libertad, 123, Madrid',
                'descripcion_restaurante' => 'Restaurante tradicional español con cocina mediterránea.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 35.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'la_torre_de_oro.jpg',
                'nombre_gerente' => 'Juan Pérez',
                'email_gerente' => 'juan.perez@latorredeoro.com',
            ],
            [
                'nombre_restaurante' => 'Sazón Ibérica',
                'ubicacion_restaurante' => 'Calle Gran Vía, 456, Barcelona',
                'descripcion_restaurante' => 'Restaurante especializado en carnes ibéricas y vinos.',
                'horario_restaurante' => 'Martes a Domingo: 12:00 PM a 11:00 PM',
                'precio_restaurante' => 50.00,
                'valoracion_media' => 4.8,
                'img_restaurante' => 'sazon_ibERICA.jpg',
                'nombre_gerente' => 'María Gómez',
                'email_gerente' => 'maria.gomez@sazonibERICA.com',
            ],
            [
                'nombre_restaurante' => 'El Cuco',
                'ubicacion_restaurante' => 'Paseo de Gracia, 789, Barcelona',
                'descripcion_restaurante' => 'Restaurante moderno con cocina fusión.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 45.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_cuco.jpg',
                'nombre_gerente' => 'Carlos Martínez',
                'email_gerente' => 'carlos.martinez@elcuco.com',
            ],
            [
                'nombre_restaurante' => 'La Cevichería',
                'ubicacion_restaurante' => 'Plaza Mayor, 123, Sevilla',
                'descripcion_restaurante' => 'Restaurante especializado en ceviche y mariscos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_cevicheria.jpg',
                'nombre_gerente' => 'Ana López',
                'email_gerente' => 'ana.lopez@lacevicheria.com',
            ],
            [
                'nombre_restaurante' => 'La Huerta',
                'ubicacion_restaurante' => 'Calle Alcalá, 456, Madrid',
                'descripcion_restaurante' => 'Restaurante ecológico con ingredientes locales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 4.4,
                'img_restaurante' => 'la_huerta.jpg',
                'nombre_gerente' => 'Pedro Sánchez',
                'email_gerente' => 'pedro.sanchez@lahuerta.com',
            ],
            [
                'nombre_restaurante' => 'El Rincon Chino',
                'ubicacion_restaurante' => 'Calle de la Paz, 789, Valencia',
                'descripcion_restaurante' => 'Restaurante chino con platos auténticos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 25.00,
                'valoracion_media' => 4.3,
                'img_restaurante' => 'el_rincon_chino.jpg',
                'nombre_gerente' => 'Luis Fernández',
                'email_gerente' => 'luis.fernandez@elrinconchino.com',
            ],
            [
                'nombre_restaurante' => 'La Cocina del Mar',
                'ubicacion_restaurante' => 'Playa del Inglaterra, 123, Alicante',
                'descripcion_restaurante' => 'Restaurante con cocina marina fresca.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'la_cocina_del_mar.jpg',
                'nombre_gerente' => 'Isabel Rodríguez',
                'email_gerente' => 'isabel.rodriguez@lacocinadelmar.com',
            ],
            [
                'nombre_restaurante' => 'El Sazón',
                'ubicacion_restaurante' => 'Calle Mayor, 456, Zaragoza',
                'descripcion_restaurante' => 'Restaurante con platos tradicionales españoles.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 35.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_sazon.jpg',
                'nombre_gerente' => 'Rafael Hernández',
                'email_gerente' => 'rafael.hernandez@elsazon.com',
            ],
            [
                'nombre_restaurante' => 'El Camín',
                'ubicacion_restaurante' => 'Calle de la Justicia, 789, Granada',
                'descripcion_restaurante' => 'Restaurante con cocina andaluza tradicional.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'el_camino.jpg',
                'nombre_gerente' => 'Laura Jiménez',
                'email_gerente' => 'laura.jimenez@elcamino.com',
            ],
            [
                'nombre_restaurante' => 'La Brasa',
                'ubicacion_restaurante' => 'Avenida de los Reyes, 123, Bilbao',
                'descripcion_restaurante' => 'Restaurante con cocina asturiana y carnes a la brasa.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 45.00,
                'valoracion_media' => 4.8,
                'img_restaurante' => 'la_brasa.jpg',
                'nombre_gerente' => 'Javier López',
                'email_gerente' => 'javier.lopez@labrasa.com',
            ],
            [
                'nombre_restaurante' => 'El Rincon Andaluz',
                'ubicacion_restaurante' => 'Plaza del Ayuntamiento, 456, Sevilla',
                'descripcion_restaurante' => 'Restaurante andaluz con platos tradicionales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 35.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'el_rincon_andaluz.jpg',
                'nombre_gerente' => 'Carmen Martínez',
                'email_gerente' => 'carmen.martinez@elrinconandaluz.com',
            ],
            [
                'nombre_restaurante' => 'La Terraza',
                'ubicacion_restaurante' => 'Paseo de la Castellana, 789, Madrid',
                'descripcion_restaurante' => 'Terraza con vistas panorámicas y cocina fusión.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 50.00,
                'valoracion_media' => 4.9,
                'img_restaurante' => 'la_terrazza.jpg',
                'nombre_gerente' => 'José Ramírez',
                'email_gerente' => 'jose.ramirez@laterrezza.com',
            ],
            [
                'nombre_restaurante' => 'El Bocado',
                'ubicacion_restaurante' => 'Calle de la Paz, 123, Valencia',
                'descripcion_restaurante' => 'Restaurante con tapas y platos españoles.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 25.00,
                'valoracion_media' => 4.4,
                'img_restaurante' => 'el_bocado.jpg',
                'nombre_gerente' => 'María Fernández',
                'email_gerente' => 'maria.fernandez@elbocado.com',
            ],
            [
                'nombre_restaurante' => 'La Cervecería',
                'ubicacion_restaurante' => 'Calle de los Santos, 456, Zaragoza',
                'descripcion_restaurante' => 'Restaurante con variedad de cervezas artesanales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_cerveceria.jpg',
                'nombre_gerente' => 'Antonio García',
                'email_gerente' => 'antonio.garcia@lacerveceria.com',
            ],
            [
                'nombre_restaurante' => 'El Sazón Mediterráneo',
                'ubicacion_restaurante' => 'Plaza de la Revolución, 789, Alicante',
                'descripcion_restaurante' => 'Restaurante mediterráneo con platos auténticos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_sazon_mediterraneo.jpg',
                'nombre_gerente' => 'Isabel Torres',
                'email_gerente' => 'isabel.torres@elsazonmediterraneo.com',
            ],
            [
                'nombre_restaurante' => 'El Rincon de los Sabores',
                'ubicacion_restaurante' => 'Calle de la Marina, 123, Málaga',
                'descripcion_restaurante' => 'Restaurante con cocina fusión y platos internacionales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 45.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'el_rincon_de_los_sabores.jpg',
                'nombre_gerente' => 'Rafael Jiménez',
                'email_gerente' => 'rafael.jimenez@elrincondelossabores.com',
            ],
            [
                'nombre_restaurante' => 'La Huerta de Granada',
                'ubicacion_restaurante' => 'Calle de la Libertad, 456, Granada',
                'descripcion_restaurante' => 'Restaurante ecológico con ingredientes locales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_huerta_granada.jpg',
                'nombre_gerente' => 'Luisa Rodríguez',
                'email_gerente' => 'luisa.rodriguez@lahuertagranada.com',
            ],
            [
                'nombre_restaurante' => 'El Camín del Mar',
                'ubicacion_restaurante' => 'Playa de Levante, 789, Alicante',
                'descripcion_restaurante' => 'Restaurante con cocina marina fresca.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 4.8,
                'img_restaurante' => 'el_camino_del_mar.jpg',
                'nombre_gerente' => 'Carlos Sánchez',
                'email_gerente' => 'carlos.sanchez@elcamindelmarm.com',
            ],
            [
                'nombre_restaurante' => 'La Brasa Asturiana',
                'ubicacion_restaurante' => 'Avenida de los Reyes, 123, Bilbao',
                'descripcion_restaurante' => 'Restaurante con carnes a la brasa y cocina asturiana.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 45.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'la_brasa_asturiana.jpg',
                'nombre_gerente' => 'Ana Hernández',
                'email_gerente' => 'ana.hernandez@labrasaasturiana.com',
            ],
            [
                'nombre_restaurante' => 'El Rincon del Mediterráneo',
                'ubicacion_restaurante' => 'Plaza del Ayuntamiento, 456, Sevilla',
                'descripcion_restaurante' => 'Restaurante mediterráneo con platos auténticos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 35.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_rincon_del_mediterraneo.jpg',
                'nombre_gerente' => 'Javier Fernández',
                'email_gerente' => 'javier.fernandez@elrincondelmeterraneo.com',
            ],
            [
                'nombre_restaurante' => 'La Terraza del Sol',
                'ubicacion_restaurante' => 'Paseo de la Castellana, 789, Madrid',
                'descripcion_restaurante' => 'Terraza con vistas panorámicas y cocina fusión.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 50.00,
                'valoracion_media' => 4.9,
                'img_restaurante' => 'la_terrazza_del_sol.jpg',
                'nombre_gerente' => 'Carmen López',
                'email_gerente' => 'carmen.lopez@laterrezadelsol.com',
            ],
            [
                'nombre_restaurante' => 'El Bocado Andaluz',
                'ubicacion_restaurante' => 'Calle de la Paz, 123, Valencia',
                'descripcion_restaurante' => 'Restaurante andaluz con tapas y platos españoles.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 25.00,
                'valoracion_media' => 4.4,
                'img_restaurante' => 'el_bocado_andaluz.jpg',
                'nombre_gerente' => 'Antonio Torres',
                'email_gerente' => 'antonio.torres@elbocadoandaluz.com',
            ],
            [
                'nombre_restaurante' => 'La Cervecería Ibérica',
                'ubicacion_restaurante' => 'Calle de los Santos, 456, Zaragoza',
                'descripcion_restaurante' => 'Restaurante con cervezas artesanales y platos españoles.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_cerveceria_ibERICA.jpg',
                'nombre_gerente' => 'Isabel García',
                'email_gerente' => 'isabel.garcia@lacerveceriailERICA.com',
            ],
            [
                'nombre_restaurante' => 'El Sazón Asturiano',
                'ubicacion_restaurante' => 'Plaza de la Revolución, 789, Alicante',
                'descripcion_restaurante' => 'Restaurante asturiano con platos auténticos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_sazon_asturiano.jpg',
                'nombre_gerente' => 'Rafael Jiménez',
                'email_gerente' => 'rafael.jimenez@elsazonasturiano.com',
            ],
            [
                'nombre_restaurante' => 'La Huerta de Málaga',
                'ubicacion_restaurante' => 'Calle de la Marina, 123, Málaga',
                'descripcion_restaurante' => 'Restaurante ecológico con ingredientes locales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_huerta_malaga.jpg',
                'nombre_gerente' => 'Luisa Rodríguez',
                'email_gerente' => 'luisa.rodriguez@lahuertamalaga.com',
            ],
            [
                'nombre_restaurante' => 'El Camín del Sol',
                'ubicacion_restaurante' => 'Playa de Levante, 456, Alicante',
                'descripcion_restaurante' => 'Restaurante con cocina marina fresca.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 4.8,
                'img_restaurante' => 'el_camino_del_sol.jpg',
                'nombre_gerente' => 'Carlos Sánchez',
                'email_gerente' => 'carlos.sanchez@elcamindelsol.com',
            ],
            [
                'nombre_restaurante' => 'La Brasa Valenciano',
                'ubicacion_restaurante' => 'Avenida de los Reyes, 123, Bilbao',
                'descripcion_restaurante' => 'Restaurante con carnes a la brasa y cocina valenciana.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 45.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'la_brasa_valenciano.jpg',
                'nombre_gerente' => 'Ana Hernández',
                'email_gerente' => 'ana.hernandez@labrasavalenciano.com',
            ],
            [
                'nombre_restaurante' => 'El Rincon del Sol',
                'ubicacion_restaurante' => 'Plaza del Ayuntamiento, 456, Sevilla',
                'descripcion_restaurante' => 'Restaurante con platos andaluces y vistas panorámicas.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 35.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_rincon_del_sol.jpg',
                'nombre_gerente' => 'Javier Fernández',
                'email_gerente' => 'javier.fernandez@elrincondelsol.com',
            ],
            [
                'nombre_restaurante' => 'La Terraza de Málaga',
                'ubicacion_restaurante' => 'Paseo de la Castellana, 789, Madrid',
                'descripcion_restaurante' => 'Terraza con cocina mediterránea y vistas panorámicas.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 50.00,
                'valoracion_media' => 4.9,
                'img_restaurante' => 'la_terrazza_de_malaga.jpg',
                'nombre_gerente' => 'Carmen López',
                'email_gerente' => 'carmen.lopez@laterrezademalaga.com',
            ],
            [
                'nombre_restaurante' => 'El Bocado Valenciano',
                'ubicacion_restaurante' => 'Calle de la Paz, 456, Valencia',
                'descripcion_restaurante' => 'Restaurante valenciano con tapas y platos españoles.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 25.00,
                'valoracion_media' => 4.4,
                'img_restaurante' => 'el_bocado_valenciano.jpg',
                'nombre_gerente' => 'Antonio Torres',
                'email_gerente' => 'antonio.torres@elbocadovalenciano.com',
            ],
            [
                'nombre_restaurante' => 'La Cervecería Valenciana',
                'ubicacion_restaurante' => 'Calle de los Santos, 789, Zaragoza',
                'descripcion_restaurante' => 'Restaurante con cervezas artesanales y platos valencianos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_cerveceria_valenciana.jpg',
                'nombre_gerente' => 'Isabel García',
                'email_gerente' => 'isabel.garcia@lacerveceriavalenciana.com',
            ],
            [
                'nombre_restaurante' => 'El Sazón Andaluz',
                'ubicacion_restaurante' => 'Plaza de la Revolución, 123, Alicante',
                'descripcion_restaurante' => 'Restaurante andaluz con platos auténticos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_sazon_andaluz.jpg',
                'nombre_gerente' => 'Rafael Jiménez',
                'email_gerente' => 'rafael.jimenez@elsazonandaluz.com',
            ],
            [
                'nombre_restaurante' => 'La Huerta de Sevilla',
                'ubicacion_restaurante' => 'Calle de la Marina, 456, Málaga',
                'descripcion_restaurante' => 'Restaurante ecológico con ingredientes locales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_huerta_sevilla.jpg',
                'nombre_gerente' => 'Luisa Rodríguez',
                'email_gerente' => 'luisa.rodriguez@lahuertasevilla.com',
            ],
            [
                'nombre_restaurante' => 'El Camín del Sol',
                'ubicacion_restaurante' => 'Playa de Levante, 789, Alicante',
                'descripcion_restaurante' => 'Restaurante con cocina marina fresca.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 4.8,
                'img_restaurante' => 'el_camino_del_sol.jpg',
                'nombre_gerente' => 'Carlos Sánchez',
                'email_gerente' => 'carlos.sanchez@elcamindelsol.com',
            ],
            [
                'nombre_restaurante' => 'La Brasa Andaluza',
                'ubicacion_restaurante' => 'Avenida de los Reyes, 123, Bilbao',
                'descripcion_restaurante' => 'Restaurante con carnes a la brasa y cocina andaluza.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 45.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'la_brasa_andaluza.jpg',
                'nombre_gerente' => 'Ana Hernández',
                'email_gerente' => 'ana.hernandez@labrasaandaluza.com',
            ],
            [
                'nombre_restaurante' => 'El Rincon del Mediterráneo',
                'ubicacion_restaurante' => 'Plaza del Ayuntamiento, 456, Sevilla',
                'descripcion_restaurante' => 'Restaurante mediterráneo con platos auténticos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 35.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_rincon_del_mediterraneo.jpg',
                'nombre_gerente' => 'Javier Fernández',
                'email_gerente' => 'javier.fernandez@elrincondelmeterraneo.com',
            ],
            [
                'nombre_restaurante' => 'La Terraza de Granada',
                'ubicacion_restaurante' => 'Paseo de la Castellana, 789, Madrid',
                'descripcion_restaurante' => 'Terraza con vistas panorámicas y cocina fusión.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 50.00,
                'valoracion_media' => 4.9,
                'img_restaurante' => 'la_terrazza_de_granada.jpg',
                'nombre_gerente' => 'Carmen López',
                'email_gerente' => 'carmen.lopez@laterrezadegranada.com',
            ],
            [
                'nombre_restaurante' => 'El Bocado Asturiano',
                'ubicacion_restaurante' => 'Calle de la Paz, 123, Valencia',
                'descripcion_restaurante' => 'Restaurante asturiano con tapas y platos españoles.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 25.00,
                'valoracion_media' => 4.4,
                'img_restaurante' => 'el_bocado_asturiano.jpg',
                'nombre_gerente' => 'Antonio Torres',
                'email_gerente' => 'antonio.torres@elbocadoasturiano.com',
            ],
            [
                'nombre_restaurante' => 'La Cervecería Andaluza',
                'ubicacion_restaurante' => 'Calle de los Santos, 456, Zaragoza',
                'descripcion_restaurante' => 'Restaurante con cervezas artesanales y platos andaluces.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_cerveceria_andaluza.jpg',
                'nombre_gerente' => 'Isabel García',
                'email_gerente' => 'isabel.garcia@lacerveceriaandaluza.com',
            ],
            [
                'nombre_restaurante' => 'El Sazón Valenciano',
                'ubicacion_restaurante' => 'Plaza de la Revolución, 789, Alicante',
                'descripcion_restaurante' => 'Restaurante valenciano con paella y platos auténticos.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_sazon_valenciano.jpg',
                'nombre_gerente' => 'Rafael Jiménez',
                'email_gerente' => 'rafael.jimenez@elsazonvalenciano.com',
            ],
            [
                'nombre_restaurante' => 'La Huerta de Bilbao',
                'ubicacion_restaurante' => 'Calle de la Marina, 123, Málaga',
                'descripcion_restaurante' => 'Restaurante ecológico con ingredientes locales.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 30.00,
                'valoracion_media' => 1,
                'img_restaurante' => 'la_huerta_bilbao.jpg',
                'nombre_gerente' => 'Luisa Rodríguez',
                'email_gerente' => 'luisa.rodriguez@lahuertabilbao.com',
            ],
            [
                'nombre_restaurante' => 'El Camín del Mar',
                'ubicacion_restaurante' => 'Playa de Levante, 456, Alicante',
                'descripcion_restaurante' => 'Restaurante con cocina marina fresca.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 40.00,
                'valoracion_media' => 4.8,
                'img_restaurante' => 'el_camino_del_mar.jpg',
                'nombre_gerente' => 'Carlos Sánchez',
                'email_gerente' => 'carlos.sanchez@elcamindelmarm.com',
            ],
            [
                'nombre_restaurante' => 'La Brasa Valenciano',
                'ubicacion_restaurante' => 'Avenida de los Reyes, 123, Bilbao',
                'descripcion_restaurante' => 'Restaurante con carnes a la brasa y cocina valenciana.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 45.00,
                'valoracion_media' => 3,
                'img_restaurante' => 'la_brasa_valenciano.jpg',
                'nombre_gerente' => 'Ana Hernández',
                'email_gerente' => 'ana.hernandez@labrasavalenciano.com',
            ],
            [
                'nombre_restaurante' => 'El Rincon del Sol',
                'ubicacion_restaurante' => 'Plaza del Ayuntamiento, 456, Sevilla',
                'descripcion_restaurante' => 'Restaurante con platos andaluces y vistas panorámicas.',
                'horario_restaurante' => 'Lunes a Domingo: 12:00 PM a 10:00 PM',
                'precio_restaurante' => 35.00,
                'valoracion_media' => 2,
                'img_restaurante' => 'el_rincon_del_sol.jpg',
                'nombre_gerente' => 'Javier Fernández',
                'email_gerente' => 'javier.fernandez@elrincondelsol.com',
            ]
        ];

        foreach ($restaurantes as $restaurante) {
            Restaurante::create($restaurante);
        }
    }
}
