<?php

namespace Database\Seeders;

use App\Models\Restaurante;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RestauranteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $restaurantes = [
            [
                'nombre_restaurante' => 'Restaurante Arzak',
                'ubicacion_restaurante' => 'San Sebastián',
                'descripcion_restaurante' => 'Cocina vasca de autor con toques innovadores.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:15 PM, 8:45 PM a 11:00 PM',
                'precio_restaurante' => 250.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'arzak.jpg',
                'nombre_gerente' => 'Juan Mari Arzak',
                'email_gerente' => 'info@arzak.es',
            ],
            [
                'nombre_restaurante' => 'El Celler de Can Roca',
                'ubicacion_restaurante' => 'Girona',
                'descripcion_restaurante' => 'Cocina creativa con raíces catalanas.',
                'horario_restaurante' => 'Martes a Sábado: 12:30 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 4.2,
                'img_restaurante' => 'el_celler_de_can_roca.jpg',
                'nombre_gerente' => 'Joan Roca',
                'email_gerente' => 'info@cellercanroca.com',
            ],
            [
                'nombre_restaurante' => 'DiverXO',
                'ubicacion_restaurante' => 'Madrid',
                'descripcion_restaurante' => 'Cocina de vanguardia con influencias asiáticas.',
                'horario_restaurante' => 'Martes a Sábado: 1:30 PM a 3:00 PM, 8:30 PM a 10:30 PM',
                'precio_restaurante' => 325.00,
                'valoracion_media' => 4.9,
                'img_restaurante' => 'diverxo.jpg',
                'nombre_gerente' => 'Dabiz Muñoz',
                'email_gerente' => 'info@diverxo.com',
            ],
            [
                'nombre_restaurante' => 'Aponiente',
                'ubicacion_restaurante' => 'Cádiz',
                'descripcion_restaurante' => 'Cocina del mar con técnicas innovadoras.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.7,
                'img_restaurante' => 'aponiente.jpg',
                'nombre_gerente' => 'Ángel León',
                'email_gerente' => 'info@aponiente.com',
            ],
            [
                'nombre_restaurante' => 'Azurmendi',
                'ubicacion_restaurante' => 'Bizkaia',
                'descripcion_restaurante' => 'Cocina vasca moderna con un enfoque sostenible.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 240.00,
                'valoracion_media' => 4.5,
                'img_restaurante' => 'azurmendi.jpg',
                'nombre_gerente' => 'Eneko Atxa',
                'email_gerente' => 'info@azurmendi.com',
            ],
            [
                'nombre_restaurante' => 'Quique Dacosta',
                'ubicacion_restaurante' => 'Alicante',
                'descripcion_restaurante' => 'Cocina creativa con raíces mediterráneas.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 3.9,
                'img_restaurante' => 'quique_dacosta.jpg',
                'nombre_gerente' => 'Quique Dacosta',
                'email_gerente' => 'info@quiquedacosta.com',
            ],
            [
                'nombre_restaurante' => 'Martín Berasategui',
                'ubicacion_restaurante' => 'Gipuzkoa',
                'descripcion_restaurante' => 'Cocina vasca con un toque personal.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 250.00,
                'valoracion_media' => 4.8,
                'img_restaurante' => 'martin_berasategui.jpg',
                'nombre_gerente' => 'Martín Berasategui',
                'email_gerente' => 'info@martinberasategui.com',
            ],
            [
                'nombre_restaurante' => 'Sant Pau',
                'ubicacion_restaurante' => 'Barcelona',
                'descripcion_restaurante' => 'Cocina catalana con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 3.5,
                'img_restaurante' => 'sant_pau.jpg',
                'nombre_gerente' => 'Carme Ruscalleda',
                'email_gerente' => 'info@santpau.com',
            ],
            [
                'nombre_restaurante' => 'Mugaritz',
                'ubicacion_restaurante' => 'Gipuzkoa',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque experimental.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 260.00,
                'valoracion_media' => 4.1,
                'img_restaurante' => 'mugaritz.jpg',
                'nombre_gerente' => 'Andoni Luis Aduriz',
                'email_gerente' => 'info@mugaritz.com',
            ],
            [
                'nombre_restaurante' => 'Casa Marcial',
                'ubicacion_restaurante' => 'Asturias',
                'descripcion_restaurante' => 'Cocina asturiana con un toque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 180.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'casa_marcial.jpg',
                'nombre_gerente' => 'Nacho Manzano',
                'email_gerente' => 'info@casamarcial.com',
            ],
            [
                'nombre_restaurante' => 'Cenador de Amós',
                'ubicacion_restaurante' => 'Cantabria',
                'descripcion_restaurante' => 'Cocina cántabra con un enfoque innovador.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.6,
                'img_restaurante' => 'cenador_de_amos.jpg',
                'nombre_gerente' => 'Jesús Sánchez',
                'email_gerente' => 'info@cenadordeamos.com',
            ],
            [
                'nombre_restaurante' => 'Akelarre',
                'ubicacion_restaurante' => 'San Sebastián',
                'descripcion_restaurante' => 'Cocina vasca con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 240.00,
                'valoracion_media' => 4.4,
                'img_restaurante' => 'akelarre.jpg',
                'nombre_gerente' => 'Pedro Subijana',
                'email_gerente' => 'info@akelarre.net',
            ],
            [
                'nombre_restaurante' => 'Etxebarri',
                'ubicacion_restaurante' => 'Bizkaia',
                'descripcion_restaurante' => 'Cocina a la brasa con ingredientes de calidad.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM',
                'precio_restaurante' => 190.00,
                'valoracion_media' => 4.7,
                'img_restaurante' => 'etxebarri.jpg',
                'nombre_gerente' => 'Bittor Arginzoniz',
                'email_gerente' => 'info@etxebarri.com',
            ],
            [
                'nombre_restaurante' => 'Elkano',
                'ubicacion_restaurante' => 'Gipuzkoa',
                'descripcion_restaurante' => 'Especializado en pescados y mariscos a la parrilla.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 3.8,
                'img_restaurante' => 'elkano.jpg',
                'nombre_gerente' => 'Aitor Arregi',
                'email_gerente' => 'info@elkano.com',
            ],
            [
                'nombre_restaurante' => 'Abac',
                'ubicacion_restaurante' => 'Barcelona',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.3,
                'img_restaurante' => 'abac.jpg',
                'nombre_gerente' => 'Jordi Cruz',
                'email_gerente' => 'info@abac.com',
            ],
            [
                'nombre_restaurante' => 'El Bohío',
                'ubicacion_restaurante' => 'Toledo',
                'descripcion_restaurante' => 'Cocina manchega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 180.00,
                'valoracion_media' => 3.9,
                'img_restaurante' => 'el_bohio.jpg',
                'nombre_gerente' => 'Pepe Rodríguez',
                'email_gerente' => 'info@elbohio.com',
            ],
            [
                'nombre_restaurante' => 'Coque',
                'ubicacion_restaurante' => 'Madrid',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque innovador.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 250.00,
                'valoracion_media' => 4.6,
                'img_restaurante' => 'coque.jpg',
                'nombre_gerente' => 'Mario Sandoval',
                'email_gerente' => 'info@coque.com',
            ],
            [
                'nombre_restaurante' => 'El Portal de Echaurren',
                'ubicacion_restaurante' => 'La Rioja',
                'descripcion_restaurante' => 'Cocina riojana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.2,
                'img_restaurante' => 'el_portal_de_echaurren.jpg',
                'nombre_gerente' => 'Francis Paniego',
                'email_gerente' => 'info@echaurren.com',
            ],
            [
                'nombre_restaurante' => 'El Invernadero',
                'ubicacion_restaurante' => 'Madrid',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque sostenible.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'el_invernadero.jpg',
                'nombre_gerente' => 'Rodrigo de la Calle',
                'email_gerente' => 'info@elinvernadero.com',
            ],
            [
                'nombre_restaurante' => 'El Poblet',
                'ubicacion_restaurante' => 'Valencia',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 190.00,
                'valoracion_media' => 3.7,
                'img_restaurante' => 'el_poblet.jpg',
                'nombre_gerente' => 'Luis Valls',
                'email_gerente' => 'info@elpoblet.com',
            ],
            [
                'nombre_restaurante' => 'El Rincón de Juan Carlos',
                'ubicacion_restaurante' => 'Tenerife',
                'descripcion_restaurante' => 'Cocina canaria con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.5,
                'img_restaurante' => 'el_rincon_de_juan_carlos.jpg',
                'nombre_gerente' => 'Juan Carlos Padrón',
                'email_gerente' => 'info@elrincondejuancarlos.com',
            ],
            [
                'nombre_restaurante' => 'El Serbal',
                'ubicacion_restaurante' => 'Cantabria',
                'descripcion_restaurante' => 'Cocina cántabra con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.8,
                'img_restaurante' => 'el_serbal.jpg',
                'nombre_gerente' => 'Rafael Prieto',
                'email_gerente' => 'info@elserbal.com',
            ],
            [
                'nombre_restaurante' => 'Solana',
                'ubicacion_restaurante' => 'Cantabria',
                'descripcion_restaurante' => 'Cocina riojana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.1,
                'img_restaurante' => 'solana.jpg',
                'nombre_gerente' => 'Nacho Solana',
                'email_gerente' => 'info@eltaller.com',
            ],
            [
                'nombre_restaurante' => 'El Trigo',
                'ubicacion_restaurante' => 'León',
                'descripcion_restaurante' => 'Cocina leonesa con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.9,
                'img_restaurante' => 'el_trigo.jpg',
                'nombre_gerente' => 'Javier Rodríguez',
                'email_gerente' => 'info@eltrigo.com',
            ],
            [
                'nombre_restaurante' => 'El Txoko',
                'ubicacion_restaurante' => 'Bilbao',
                'descripcion_restaurante' => 'Cocina vasca con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.2,
                'img_restaurante' => 'el_txoko.jpg',
                'nombre_gerente' => 'Aitor Elizegi',
                'email_gerente' => 'info@eltxoko.com',
            ],
            [
                'nombre_restaurante' => 'El Ventorrillo',
                'ubicacion_restaurante' => 'Cádiz',
                'descripcion_restaurante' => 'Cocina andaluza con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.6,
                'img_restaurante' => 'el_ventorrillo.jpg',
                'nombre_gerente' => 'José Luis García',
                'email_gerente' => 'info@elventorrillo.com',
            ],
            [
                'nombre_restaurante' => 'El Zaguán',
                'ubicacion_restaurante' => 'Burgos',
                'descripcion_restaurante' => 'Cocina castellana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'el_zaguan.jpg',
                'nombre_gerente' => 'Fernando Pérez',
                'email_gerente' => 'info@elzaguan.com',
            ],
            [
                'nombre_restaurante' => 'Eneko',
                'ubicacion_restaurante' => 'Bizkaia',
                'descripcion_restaurante' => 'Cocina vasca con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.3,
                'img_restaurante' => 'eneko.jpg',
                'nombre_gerente' => 'Eneko Atxa',
                'email_gerente' => 'info@eneko.com',
            ],
            [
                'nombre_restaurante' => 'Es Fum',
                'ubicacion_restaurante' => 'Mallorca',
                'descripcion_restaurante' => 'Cocina balear con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.7,
                'img_restaurante' => 'es_fum.jpg',
                'nombre_gerente' => 'Miguel Navarro',
                'email_gerente' => 'info@esfum.com',
            ],
            [
                'nombre_restaurante' => 'Fonda Sala',
                'ubicacion_restaurante' => 'Olot',
                'descripcion_restaurante' => 'Cocina catalana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.1,
                'img_restaurante' => 'fonda_sala.jpg',
                'nombre_gerente' => 'Toni Sala',
                'email_gerente' => 'info@fondasala.com',
            ],
            [
                'nombre_restaurante' => 'Gresca',
                'ubicacion_restaurante' => 'Barcelona',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 180.00,
                'valoracion_media' => 3.9,
                'img_restaurante' => 'gresca.jpg',
                'nombre_gerente' => 'Rafa Peña',
                'email_gerente' => 'info@gresca.com',
            ],
            [
                'nombre_restaurante' => 'Hofmann',
                'ubicacion_restaurante' => 'Barcelona',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 190.00,
                'valoracion_media' => 4.2,
                'img_restaurante' => 'hofmann.jpg',
                'nombre_gerente' => 'Mey Hofmann',
                'email_gerente' => 'info@hofmann.com',
            ],
            [
                'nombre_restaurante' => 'Kaleja',
                'ubicacion_restaurante' => 'Málaga',
                'descripcion_restaurante' => 'Cocina andaluza con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 3.8,
                'img_restaurante' => 'kaleja.jpg',
                'nombre_gerente' => 'Dani Carnero',
                'email_gerente' => 'info@kaleja.com',
            ],
            [
                'nombre_restaurante' => 'Kiro Sushi',
                'ubicacion_restaurante' => 'Logroño',
                'descripcion_restaurante' => 'Cocina japonesa con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'kiro_sushi.jpg',
                'nombre_gerente' => 'Félix Jiménez',
                'email_gerente' => 'info@kirosushi.com',
            ],
            [
                'nombre_restaurante' => 'La Boscana',
                'ubicacion_restaurante' => 'Lleida',
                'descripcion_restaurante' => 'Cocina catalana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.3,
                'img_restaurante' => 'la_boscana.jpg',
                'nombre_gerente' => 'Joel Castanyé',
                'email_gerente' => 'info@laboscana.com',
            ],
            [
                'nombre_restaurante' => 'La Cabaña',
                'ubicacion_restaurante' => 'Murcia',
                'descripcion_restaurante' => 'Cocina murciana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 3.7,
                'img_restaurante' => 'la_cabana.jpg',
                'nombre_gerente' => 'Pablo González',
                'email_gerente' => 'info@lacabanamurcia.com',
            ],
            [
                'nombre_restaurante' => 'La Finca',
                'ubicacion_restaurante' => 'Alicante',
                'descripcion_restaurante' => 'Cocina mediterránea con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 4.1,
                'img_restaurante' => 'la_finca.jpg',
                'nombre_gerente' => 'Susi Díaz',
                'email_gerente' => 'info@lafinca.com',
            ],
            [
                'nombre_restaurante' => 'La Salita',
                'ubicacion_restaurante' => 'Valencia',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 3.9,
                'img_restaurante' => 'la_salita.jpg',
                'nombre_gerente' => 'Begoña Rodrigo',
                'email_gerente' => 'info@lasalita.com',
            ],
            [
                'nombre_restaurante' => 'Lúa',
                'ubicacion_restaurante' => 'Madrid',
                'descripcion_restaurante' => 'Cocina gallega con un toque de autor.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.2,
                'img_restaurante' => 'lua.jpg',
                'nombre_gerente' => 'Manuel Domínguez',
                'email_gerente' => 'info@lua.com',
            ],
            [
                'nombre_restaurante' => 'Maralba',
                'ubicacion_restaurante' => 'Albacete',
                'descripcion_restaurante' => 'Cocina manchega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.8,
                'img_restaurante' => 'maralba.jpg',
                'nombre_gerente' => 'Fran Martínez',
                'email_gerente' => 'info@maralba.com',
            ],
            [
                'nombre_restaurante' => 'Monastrell',
                'ubicacion_restaurante' => 'Alicante',
                'descripcion_restaurante' => 'Cocina mediterránea con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'monastrell.jpg',
                'nombre_gerente' => 'María José San Román',
                'email_gerente' => 'info@monastrell.com',
            ],
            [
                'nombre_restaurante' => 'Noor',
                'ubicacion_restaurante' => 'Córdoba',
                'descripcion_restaurante' => 'Cocina andaluza con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 4.3,
                'img_restaurante' => 'noor.jpg',
                'nombre_gerente' => 'Paco Morales',
                'email_gerente' => 'info@noor.com',
            ],
            [
                'nombre_restaurante' => 'Orobianco',
                'ubicacion_restaurante' => 'Alicante',
                'descripcion_restaurante' => 'Cocina italiana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.7,
                'img_restaurante' => 'orobianco.jpg',
                'nombre_gerente' => 'Enrico Croatti',
                'email_gerente' => 'info@orobianco.com',
            ],
            [
                'nombre_restaurante' => 'Pepe Vieira',
                'ubicacion_restaurante' => 'Pontevedra',
                'descripcion_restaurante' => 'Cocina gallega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.1,
                'img_restaurante' => 'pepe_vieira.jpg',
                'nombre_gerente' => 'Xosé Cannas',
                'email_gerente' => 'info@pepevieira.com',
            ],
            [
                'nombre_restaurante' => 'Ricard Camarena',
                'ubicacion_restaurante' => 'Valencia',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 4.4,
                'img_restaurante' => 'ricard_camarena.jpg',
                'nombre_gerente' => 'Ricard Camarena',
                'email_gerente' => 'info@ricardcamarena.com',
            ],
            [
                'nombre_restaurante' => 'Rodero',
                'ubicacion_restaurante' => 'Navarra',
                'descripcion_restaurante' => 'Cocina navarra con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.9,
                'img_restaurante' => 'rodero.jpg',
                'nombre_gerente' => 'Koldo Rodero',
                'email_gerente' => 'info@rodero.com',
            ],
            [
                'nombre_restaurante' => 'Sollo',
                'ubicacion_restaurante' => 'Málaga',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque sostenible.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'sollo.jpg',
                'nombre_gerente' => 'Diego Gallegos',
                'email_gerente' => 'info@sollo.com',
            ],
            [
                'nombre_restaurante' => 'Via Veneto',
                'ubicacion_restaurante' => 'Barcelona',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque histórico.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 165.00,
                'valoracion_media' => 3.8,
                'img_restaurante' => 'via_veneto.jpg',
                'nombre_gerente' => 'Javier Oliveira',
                'email_gerente' => 'info@viaveneto.com',
            ],
            [
                'nombre_restaurante' => 'Tatau',
                'ubicacion_restaurante' => 'Huesca',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.2,
                'img_restaurante' => 'tatau.jpg',
                'nombre_gerente' => 'Tonino Valiente',
                'email_gerente' => 'info@tatau.com',
            ],
            [
                'nombre_restaurante' => 'Trivio',
                'ubicacion_restaurante' => 'Cuenca',
                'descripcion_restaurante' => 'Cocina manchega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.7,
                'img_restaurante' => 'trivio.jpg',
                'nombre_gerente' => 'Jesús Segura',
                'email_gerente' => 'info@trivio.com',
            ],
            [
                'nombre_restaurante' => 'Zaranda',
                'ubicacion_restaurante' => 'Mallorca',
                'descripcion_restaurante' => 'Cocina balear con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 4.1,
                'img_restaurante' => 'zaranda.jpg',
                'nombre_gerente' => 'Fernando P. Arellano',
                'email_gerente' => 'info@zaranda.com',
            ]
        ];

        foreach ($restaurantes as $restaurante) {
            Restaurante::create($restaurante);
        }
    }
}
