<?php

namespace Database\Seeders;

use App\Models\Restaurante;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RestauranteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $restaurantes = [
            [
                'nombre_restaurante' => 'Restaurante Arzak',
                'ubicacion_restaurante' => 'Alcalde J. Elosegi Hiribidea, 273, 20015',
                'descripcion_restaurante' => 'Cocina vasca de autor con toques innovadores.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:15 PM, 8:45 PM a 11:00 PM',
                'precio_restaurante' => 250.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'arzak.jpg',
                'nombre_gerente' => 'Juan Mari Arzak',
                'email_gerente' => 'info@arzak.es',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 23,
            ],
            [
                'nombre_restaurante' => 'El Celler de Can Roca',
                'ubicacion_restaurante' => 'Carrer de Can Sunyer, 48, 17007',
                'descripcion_restaurante' => 'Cocina creativa con raíces catalanas.',
                'horario_restaurante' => 'Martes a Sábado: 12:30 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'el_celler_de_can_roca.jpg',
                'nombre_gerente' => 'Joan Roca',
                'email_gerente' => 'info@cellercanroca.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 20
            ],
            [
                'nombre_restaurante' => 'DiverXO',
                'ubicacion_restaurante' => 'NH Eurobuilding, C. del Padre Damián, 23, Chamartín, 28036',
                'descripcion_restaurante' => 'Cocina de vanguardia con influencias asiáticas.',
                'horario_restaurante' => 'Martes a Sábado: 1:30 PM a 3:00 PM, 8:30 PM a 10:30 PM',
                'precio_restaurante' => 325.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'diverxo.jpg',
                'nombre_gerente' => 'Dabiz Muñoz',
                'email_gerente' => 'info@diverxo.com',
                'id_comunidad_autonoma' => 15,
                'id_provincia' => 30
            ],
            [
                'nombre_restaurante' => 'Aponiente',
                'ubicacion_restaurante' => 'Calle Francisco Cossi Ochoa, s/n, 11500, Molino de Mareas El Caño',
                'descripcion_restaurante' => 'Cocina del mar con técnicas innovadoras.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'aponiente.jpg',
                'nombre_gerente' => 'Ángel León',
                'email_gerente' => 'info@aponiente.com',
                'id_comunidad_autonoma' => 1,
                'id_provincia' => 12
            ],
            [
                'nombre_restaurante' => 'Azurmendi',
                'ubicacion_restaurante' => 'Barrio Leguina, s/n, 48195 Larrabetzu',
                'descripcion_restaurante' => 'Cocina vasca moderna con un enfoque sostenible.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 240.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'azurmendi.jpg',
                'nombre_gerente' => 'Eneko Atxa',
                'email_gerente' => 'info@azurmendi.com',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 50
            ],
            [
                'nombre_restaurante' => 'Quique Dacosta',
                'ubicacion_restaurante' => 'Carrer Rascassa, 1, 03700 Dénia',
                'descripcion_restaurante' => 'Cocina creativa con raíces mediterráneas.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 2.0,
                'img_restaurante' => 'quique_dacosta.jpg',
                'nombre_gerente' => 'Quique Dacosta',
                'email_gerente' => 'info@quiquedacosta.com',
                'id_comunidad_autonoma' => 11,
                'id_provincia' => 3
            ],
            [
                'nombre_restaurante' => 'Martín Berasategui',
                'ubicacion_restaurante' => 'Loidi Kalea, 4, 20160 Lasarte-Oria',
                'descripcion_restaurante' => 'Cocina vasca con un toque personal.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 250.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'martin_berasategui.jpg',
                'nombre_gerente' => 'Martín Berasategui',
                'email_gerente' => 'info@martinberasategui.com',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 23
            ],
            [
                'nombre_restaurante' => 'Sant Pau',
                'ubicacion_restaurante' => 'Carrer Nou, 10, 08395 Sant Pol de Mar',
                'descripcion_restaurante' => 'Cocina catalana con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'sant_pau.jpg',
                'nombre_gerente' => 'Carme Ruscalleda',
                'email_gerente' => 'info@santpau.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 9
            ],
            [
                'nombre_restaurante' => 'Mugaritz',
                'ubicacion_restaurante' => 'Aldura Aldea, 20, 20100 Errenteria',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque experimental.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 260.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'mugaritz.jpg',
                'nombre_gerente' => 'Andoni Luis Aduriz',
                'email_gerente' => 'info@mugaritz.com',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 23,
            ],
            [
                'nombre_restaurante' => 'Casa Marcial',
                'ubicacion_restaurante' => 'Calle La Salgar, s/n, 33549 Arriondas, Parres',
                'descripcion_restaurante' => 'Cocina asturiana con un toque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 180.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'casa_marcial.jpg',
                'nombre_gerente' => 'Nacho Manzano',
                'email_gerente' => 'info@casamarcial.com',
                'id_comunidad_autonoma' => 3,
                'id_provincia' => 5,
            ],
            [
                'nombre_restaurante' => 'Cenador de Amós',
                'ubicacion_restaurante' => 'Plaza del Sol, s/n, 39793 Villaverde de Pontones',
                'descripcion_restaurante' => 'Cocina cántabra con un enfoque innovador.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'cenador_de_amos.jpg',
                'nombre_gerente' => 'Jesús Sánchez',
                'email_gerente' => 'info@cenadordeamos.com',
                'id_comunidad_autonoma' => 6,
                'id_provincia' => 13,
            ],
            [
                'nombre_restaurante' => 'Akelarre',
                'ubicacion_restaurante' => 'Padre Orcolaga, 56 (Igeldo), 20008',
                'descripcion_restaurante' => 'Cocina vasca con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 240.00,
                'valoracion_media' => 1.0,
                'img_restaurante' => 'akelarre.jpg',
                'nombre_gerente' => 'Pedro Subijana',
                'email_gerente' => 'info@akelarre.net',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 23,
            ],
            [
                'nombre_restaurante' => 'Etxebarri',
                'ubicacion_restaurante' => 'Bizkaia',
                'descripcion_restaurante' => 'Cocina a la brasa con ingredientes de calidad.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM',
                'precio_restaurante' => 190.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'etxebarri.jpg',
                'nombre_gerente' => 'Bittor Arginzoniz',
                'email_gerente' => 'info@etxebarri.com',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 50,
            ],
            [
                'nombre_restaurante' => 'Elkano',
                'ubicacion_restaurante' => 'Herrerieta Kalea, 2, 20808 Getaria',
                'descripcion_restaurante' => 'Especializado en pescados y mariscos a la parrilla.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'elkano.jpg',
                'nombre_gerente' => 'Aitor Arregi',
                'email_gerente' => 'info@elkano.com',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 23,
            ],
            [
                'nombre_restaurante' => 'Abac',
                'ubicacion_restaurante' => 'Av. del Tibidabo, 1, Sarrià-Sant Gervasi, 08022',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'abac.jpg',
                'nombre_gerente' => 'Jordi Cruz',
                'email_gerente' => 'info@abac.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 9,
            ],
            [
                'nombre_restaurante' => 'El Bohío',
                'ubicacion_restaurante' => 'Av. Castilla La Mancha, 81, 45200 Illescas',
                'descripcion_restaurante' => 'Cocina manchega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 180.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'el_bohio.jpg',
                'nombre_gerente' => 'Pepe Rodríguez',
                'email_gerente' => 'info@elbohio.com',
                'id_comunidad_autonoma' => 7,
                'id_provincia' => 47,
            ],
            [
                'nombre_restaurante' => 'Coque',
                'ubicacion_restaurante' => 'C. del Marqués del Riscal, 11, Chamberí, 28010',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque innovador.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 250.00,
                'valoracion_media' => 4.6,
                'img_restaurante' => 'coque.jpg',
                'nombre_gerente' => 'Mario Sandoval',
                'email_gerente' => 'info@coque.com',
                'id_comunidad_autonoma' => 15,
                'id_provincia' => 30,
            ],
            [
                'nombre_restaurante' => 'El Portal de Echaurren',
                'ubicacion_restaurante' => 'C. Padre Jose Garcia, 19, 26280 Ezcaray',
                'descripcion_restaurante' => 'Cocina riojana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 2.0,
                'img_restaurante' => 'el_portal_de_echaurren.jpg',
                'nombre_gerente' => 'Francis Paniego',
                'email_gerente' => 'info@echaurren.com',
                'id_comunidad_autonoma' => 14,
                'id_provincia' => 39,
            ],
            [
                'nombre_restaurante' => 'El Invernadero',
                'ubicacion_restaurante' => 'C/ de Ponzano, 85, Chamberí, 28003',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque sostenible.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'el_invernadero.jpg',
                'nombre_gerente' => 'Rodrigo de la Calle',
                'email_gerente' => 'info@elinvernadero.com',
                'id_comunidad_autonoma' => 15,
                'id_provincia' => 30,
            ],
            [
                'nombre_restaurante' => 'El Poblet',
                'ubicacion_restaurante' => 'C/ de Correus, 8, Ciutat Vella, 46002',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 190.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'el_poblet.jpg',
                'nombre_gerente' => 'Luis Valls',
                'email_gerente' => 'info@elpoblet.com',
                'id_comunidad_autonoma' => 11,
                'id_provincia' => 48,
            ],
            [
                'nombre_restaurante' => 'El Rincón de Juan Carlos',
                'ubicacion_restaurante' => 'Royal Hideaway Corales Beach, Av. de la Virgen de Guadalupe, 21, 5ª Planta, 38679 Adeje',
                'descripcion_restaurante' => 'Cocina canaria con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'el_rincon_de_juan_carlos.jpg',
                'nombre_gerente' => 'Juan Carlos Padrón',
                'email_gerente' => 'info@elrincondejuancarlos.com',
                'id_comunidad_autonoma' => 5,
                'id_provincia' => 41,
            ],
            [
                'nombre_restaurante' => 'El Serbal',
                'ubicacion_restaurante' => 'Av. Manuel García Lago, 1E, 39005 Santander',
                'descripcion_restaurante' => 'Cocina cántabra con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'el_serbal.jpg',
                'nombre_gerente' => 'Rafael Prieto',
                'email_gerente' => 'info@elserbal.com',
                'id_comunidad_autonoma' => 6,
                'id_provincia' => 13,
            ],
            [
                'nombre_restaurante' => 'Solana',
                'ubicacion_restaurante' => 'La Bien Aparecida, 11, 39849 Ampuero',
                'descripcion_restaurante' => 'Cocina riojana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'solana.jpg',
                'nombre_gerente' => 'Nacho Solana',
                'email_gerente' => 'info@eltaller.com',
                'id_comunidad_autonoma' => 6,
                'id_provincia' => 13,
            ],
            [
                'nombre_restaurante' => 'El Trigo',
                'ubicacion_restaurante' => 'C. Tintes, 8, 47002',
                'descripcion_restaurante' => 'Cocina vallisoletana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'el_trigo.jpg',
                'nombre_gerente' => 'Javier Rodríguez',
                'email_gerente' => 'info@eltrigo.com',
                'id_comunidad_autonoma' => 8,
                'id_provincia' => 49,
            ],
            [
                'nombre_restaurante' => 'El Txoko',
                'ubicacion_restaurante' => 'C. Bidebarrieta Kalea, 14, Ibaiondo, 48005',
                'descripcion_restaurante' => 'Cocina vasca con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'el_txoko.jpg',
                'nombre_gerente' => 'Aitor Elizegi',
                'email_gerente' => 'info@eltxoko.com',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 50,
            ],
            [
                'nombre_restaurante' => 'El Ventorrillo',
                'ubicacion_restaurante' => 'Av. Vía Augusta Julia, 11011',
                'descripcion_restaurante' => 'Cocina andaluza con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.6,
                'img_restaurante' => 'el_ventorrillo.jpg',
                'nombre_gerente' => 'José Luis García',
                'email_gerente' => 'info@elventorrillo.com',
                'id_comunidad_autonoma' => 1,
                'id_provincia' => 12,
            ],
            [
                'nombre_restaurante' => 'El Zaguán de Salamanca',
                'ubicacion_restaurante' => 'C. Ventura Ruiz Aguilera, 7, 37002',
                'descripcion_restaurante' => 'Cocina castellana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'el_zaguan.jpg',
                'nombre_gerente' => 'Fernando Pérez',
                'email_gerente' => 'info@elzaguan.com',
                'id_comunidad_autonoma' => 8,
                'id_provincia' => 40,
            ],
            [
                'nombre_restaurante' => 'Eneko',
                'ubicacion_restaurante' => 'Barrio Legina, s/n, 48195 Larrabetzu',
                'descripcion_restaurante' => 'Cocina vasca con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'eneko.jpg',
                'nombre_gerente' => 'Eneko Atxa',
                'email_gerente' => 'info@eneko.com',
                'id_comunidad_autonoma' => 19,
                'id_provincia' => 50,
            ],
            [
                'nombre_restaurante' => 'Es Fum',
                'ubicacion_restaurante' => 'St. Regis Mardavall. Ctra. MA-20, Palma - Andratx',
                'descripcion_restaurante' => 'Cocina balear con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'es_fum.jpg',
                'nombre_gerente' => 'Miguel Navarro',
                'email_gerente' => 'info@esfum.com',
                'id_comunidad_autonoma' => 4,
                'id_provincia' => 8,
            ],
            [
                'nombre_restaurante' => 'Fonda Sala',
                'ubicacion_restaurante' => 'Pl. Major, 17, 08516, Olot',
                'descripcion_restaurante' => 'Cocina catalana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'fonda_sala.jpg',
                'nombre_gerente' => 'Toni Sala',
                'email_gerente' => 'info@fondasala.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 20,
            ],
            [
                'nombre_restaurante' => 'Gresca',
                'ubicacion_restaurante' => 'Carrer de Provença, 230, Eixample, 08036',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 180.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'gresca.jpg',
                'nombre_gerente' => 'Rafa Peña',
                'email_gerente' => 'info@gresca.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 9,
            ],
            [
                'nombre_restaurante' => 'Hofmann',
                'ubicacion_restaurante' => 'Carrer de la Granada del Penedès, 14-16, Sarrià-Sant Gervasi, 08006',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 190.00,
                'valoracion_media' => 2.0,
                'img_restaurante' => 'hofmann.jpg',
                'nombre_gerente' => 'Mey Hofmann',
                'email_gerente' => 'info@hofmann.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 9,
            ],
            [
                'nombre_restaurante' => 'Kaleja',
                'ubicacion_restaurante' => 'C. Marquesa de Moya, 9, Distrito Centro, 29015',
                'descripcion_restaurante' => 'Cocina andaluza con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 1.0,
                'img_restaurante' => 'kaleja.jpg',
                'nombre_gerente' => 'Dani Carnero',
                'email_gerente' => 'info@kaleja.com',
                'id_comunidad_autonoma' => 1,
                'id_provincia' => 33,
            ],
            [
                'nombre_restaurante' => 'Kiro Sushi',
                'ubicacion_restaurante' => 'C. Emilia Pardo Bazán, 5, 26009 Logroño',
                'descripcion_restaurante' => 'Cocina japonesa con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 2.0,
                'img_restaurante' => 'kiro_sushi.jpg',
                'nombre_gerente' => 'Félix Jiménez',
                'email_gerente' => 'info@kirosushi.com',
                'id_comunidad_autonoma' => 14,
                'id_provincia' => 39,
            ],
            [
                'nombre_restaurante' => 'La Boscana',
                'ubicacion_restaurante' => 'LV-3311, 4, 25142 Bellvís',
                'descripcion_restaurante' => 'Cocina catalana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'la_boscana.jpg',
                'nombre_gerente' => 'Joel Castanyé',
                'email_gerente' => 'info@laboscana.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 29,
            ],
            [
                'nombre_restaurante' => 'La Cabaña',
                'ubicacion_restaurante' => 'Urbanización Colonia Buenavista, Finca Buenavista S/N, 30120 El Palmar O Lugar De Don Juan',
                'descripcion_restaurante' => 'Cocina murciana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'la_cabana.jpg',
                'nombre_gerente' => 'Pablo González',
                'email_gerente' => 'info@lacabanamurcia.com',
                'id_comunidad_autonoma' => 17,
                'id_provincia' => 33,
            ],
            [
                'nombre_restaurante' => 'La Finca',
                'ubicacion_restaurante' => 'Camí de Perleta, 1, 7, 03295 Elche',
                'descripcion_restaurante' => 'Cocina mediterránea con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 1.0,
                'img_restaurante' => 'la_finca.jpg',
                'nombre_gerente' => 'Susi Díaz',
                'email_gerente' => 'info@lafinca.com',
                'id_comunidad_autonoma' => 11,
                'id_provincia' => 3,
            ],
            [
                'nombre_restaurante' => 'La Salita',
                'ubicacion_restaurante' => 'C/ de Pere III el Gran, 11, Eixample, 46005',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'la_salita.jpg',
                'nombre_gerente' => 'Begoña Rodrigo',
                'email_gerente' => 'info@lasalita.com',
                'id_comunidad_autonoma' => 11,
                'id_provincia' => 48,
            ],
            [
                'nombre_restaurante' => 'Lúa',
                'ubicacion_restaurante' => 'P.º de Eduardo Dato, 5, Chamberí, 28010',
                'descripcion_restaurante' => 'Cocina gallega con un toque de autor.',
                'horario_restaurante' => 'Martes a Sábado: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'lua.jpg',
                'nombre_gerente' => 'Manuel Domínguez',
                'email_gerente' => 'info@lua.com',
                'id_comunidad_autonoma' => 15,
                'id_provincia' => 30,
            ],
            [
                'nombre_restaurante' => 'Maralba',
                'ubicacion_restaurante' => 'C. Violeta Parra, 5, 02640 Almansa',
                'descripcion_restaurante' => 'Cocina manchega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 2.0,
                'img_restaurante' => 'maralba.jpg',
                'nombre_gerente' => 'Fran Martínez',
                'email_gerente' => 'info@maralba.com',
                'id_comunidad_autonoma' => 7,
                'id_provincia' => 2,
            ],
            [
                'nombre_restaurante' => 'Monastrell',
                'ubicacion_restaurante' => 'Av. del Almte. Julio Guillén Tato, 1, 03001',
                'descripcion_restaurante' => 'Cocina mediterránea con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'monastrell.jpg',
                'nombre_gerente' => 'María José San Román',
                'email_gerente' => 'info@monastrell.com',
                'id_comunidad_autonoma' => 11,
                'id_provincia' => 3,
            ],
            [
                'nombre_restaurante' => 'Noor',
                'ubicacion_restaurante' => 'C. Pablo Ruiz Picasso, 8, Sureste, 14014',
                'descripcion_restaurante' => 'Cocina andaluza con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'noor.jpg',
                'nombre_gerente' => 'Paco Morales',
                'email_gerente' => 'info@noor.com',
                'id_comunidad_autonoma' => 1,
                'id_provincia' => 17,
            ],
            [
                'nombre_restaurante' => 'Orobianco',
                'ubicacion_restaurante' => 'Partida Colina del Sol, 49A, 03710 Calpe',
                'descripcion_restaurante' => 'Cocina italiana con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'orobianco.jpg',
                'nombre_gerente' => 'Enrico Croatti',
                'email_gerente' => 'info@orobianco.com',
                'id_comunidad_autonoma' => 11,
                'id_provincia' => 3,
            ],
            [
                'nombre_restaurante' => 'Pepe Vieira',
                'ubicacion_restaurante' => 'Camiño Serpe, s/n, 36992 Raxó',
                'descripcion_restaurante' => 'Cocina gallega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'pepe_vieira.jpg',
                'nombre_gerente' => 'Xosé Cannas',
                'email_gerente' => 'info@pepevieira.com',
                'id_comunidad_autonoma' => 13,
                'id_provincia' => 38,
            ],
            [
                'nombre_restaurante' => 'Ricard Camarena',
                'ubicacion_restaurante' => 'Carrer de Jorge Juan, 19 (Planta Inferior), 46004',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 2.0,
                'img_restaurante' => 'ricard_camarena.jpg',
                'nombre_gerente' => 'Ricard Camarena',
                'email_gerente' => 'info@ricardcamarena.com',
                'id_comunidad_autonoma' => 11,
                'id_provincia' => 48,
            ],
            [
                'nombre_restaurante' => 'Rodero',
                'ubicacion_restaurante' => 'C. de Emilio Arrieta, 3, 31002 Pamplona',
                'descripcion_restaurante' => 'Cocina navarra con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'rodero.jpg',
                'nombre_gerente' => 'Koldo Rodero',
                'email_gerente' => 'info@rodero.com',
                'id_comunidad_autonoma' => 18,
                'id_provincia' => 34,
            ],
            [
                'nombre_restaurante' => 'Sollo',
                'ubicacion_restaurante' => 'Urbanización Reserva del Higuerón, Av. del Higuerón, 48, 29640 Fuengirola',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque sostenible.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 220.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'sollo.jpg',
                'nombre_gerente' => 'Diego Gallegos',
                'email_gerente' => 'info@sollo.com',
                'id_comunidad_autonoma' => 1,
                'id_provincia' => 31,
            ],
            [
                'nombre_restaurante' => 'Via Veneto',
                'ubicacion_restaurante' => 'Carrer de Ganduxer, 10, Sarrià-Sant Gervasi, 08021',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque histórico.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 165.00,
                'valoracion_media' => 5.0,
                'img_restaurante' => 'via_veneto.jpg',
                'nombre_gerente' => 'Javier Oliveira',
                'email_gerente' => 'info@viaveneto.com',
                'id_comunidad_autonoma' => 9,
                'id_provincia' => 9,
            ],
            [
                'nombre_restaurante' => 'Tatau',
                'ubicacion_restaurante' => 'C. Azara, s/n, 22002',
                'descripcion_restaurante' => 'Cocina de autor con un enfoque moderno.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 200.00,
                'valoracion_media' => 4.0,
                'img_restaurante' => 'tatau.jpg',
                'nombre_gerente' => 'Tonino Valiente',
                'email_gerente' => 'info@tatau.com',
                'id_comunidad_autonoma' => 2,
                'id_provincia' => 25,
            ],
            [
                'nombre_restaurante' => 'Trivio',
                'ubicacion_restaurante' => 'C. Colón, 25, 16002',
                'descripcion_restaurante' => 'Cocina manchega con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 210.00,
                'valoracion_media' => 3.0,
                'img_restaurante' => 'trivio.jpg',
                'nombre_gerente' => 'Jesús Segura',
                'email_gerente' => 'info@trivio.com',
                'id_comunidad_autonoma' => 7,
                'id_provincia' => 19,
            ],
            [
                'nombre_restaurante' => 'Zaranda',
                'ubicacion_restaurante' => 'Hotel Es Princep, C/ Bala Roja, 1, 07001',
                'descripcion_restaurante' => 'Cocina balear con un toque de autor.',
                'horario_restaurante' => 'Miércoles a Domingo: 1:00 PM a 3:00 PM, 8:00 PM a 10:30 PM',
                'precio_restaurante' => 230.00,
                'valoracion_media' => 2.0,
                'img_restaurante' => 'zaranda.jpg',
                'nombre_gerente' => 'Fernando P. Arellano',
                'email_gerente' => 'info@zaranda.com',
                'id_comunidad_autonoma' => 7,
                'id_provincia' => 47,
            ]
        ];

        foreach ($restaurantes as $restaurante) {
            Restaurante::create($restaurante);
        }
    }
}
